// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ExpandCardController from "./expand_card_controller"
application.register("expand-card", ExpandCardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SetActiveNavlinkController from "./set_active_navlink_controller"
application.register("set-active-navlink", SetActiveNavlinkController)

import SetProgressBarColorController from "./set_progress_bar_color_controller"
application.register("set-progress-bar-color", SetProgressBarColorController)

import ShowController from "./show_controller"
application.register("show", ShowController)

import SpinnerController from "./spinner_controller"
application.register("spinner", SpinnerController)
